/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package campusLink;


import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import net.proteanit.sql.DbUtils;
import java.sql.DatabaseMetaData;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author subod
 */
public class FacultyFrame extends javax.swing.JFrame {

    /**
     * Creates new form FacultyFrame
     */
    
    private static final String url = "jdbc:mysql://127.0.0.1:3306/javaportal?zeroDateTimeBehavior=CONVERT_TO_NULL";
    private static final String usrn = "SAGA";
    private static final String pass = "JAVASAGA@123";
    FacultyBackEnd fbe = new FacultyBackEnd();
    public FacultyFrame() {
        initComponents();setVisible(true);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (int) screenSize.getWidth();
        int height = (int) screenSize.getHeight();
        setSize(width, height);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        cardsL = new javax.swing.JPanel();
        maincard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        welcomename = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addusrbtn = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        searchusrbtn = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        attendcard = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        attenTable = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        day = new javax.swing.JComboBox<>();
        month = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        studentmarkscard = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        studentMarksTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        idnoLabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        regSearch = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        updatecard = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        addusrcard = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        resultcard = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(200);

        jPanel2.setBackground(new java.awt.Color(1, 1, 1));

        jLabel2.setBackground(new java.awt.Color(1, 1, 1));
        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(252, 248, 239));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DASHBOARD");

        jButton1.setBackground(new java.awt.Color(1, 1, 1));
        jButton1.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(252, 248, 239));
        jButton1.setText("BACK");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton1.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(245, 192, 0));
        jLabel7.setText("ATTENDANCE");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(245, 192, 0));
        jLabel10.setText("MARKS");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(245, 192, 0));
        jLabel25.setText("LOGOUT");
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel10))
                                .addGap(66, 66, 66))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(21, 21, 21))
        );

        jSplitPane1.setLeftComponent(jPanel2);

        cardsL.setLayout(new java.awt.CardLayout());

        maincard.setBackground(new java.awt.Color(252, 248, 239));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1.setText("WELCOME");

        welcomename.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        welcomename.setForeground(new java.awt.Color(245, 192, 0));
        welcomename.setText("ABINASH");

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(1, 1, 1));
        jLabel4.setText("FACULTY");

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(245, 192, 0));
        jLabel5.setText("MENU");

        addusrbtn.setBackground(new java.awt.Color(245, 192, 0));
        addusrbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addusrbtn.setPreferredSize(new java.awt.Dimension(200, 200));
        addusrbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addusrbtnMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(1, 1, 1));
        jLabel6.setText("ATTENDANCE");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/campusLink/Resources/atten_logo.png"))); // NOI18N

        javax.swing.GroupLayout addusrbtnLayout = new javax.swing.GroupLayout(addusrbtn);
        addusrbtn.setLayout(addusrbtnLayout);
        addusrbtnLayout.setHorizontalGroup(
            addusrbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addusrbtnLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(addusrbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel6))
                .addGap(37, 37, 37))
        );
        addusrbtnLayout.setVerticalGroup(
            addusrbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addusrbtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        searchusrbtn.setBackground(new java.awt.Color(245, 192, 0));
        searchusrbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchusrbtn.setPreferredSize(new java.awt.Dimension(200, 200));
        searchusrbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchusrbtnMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(1, 1, 1));
        jLabel8.setText("MARKS");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/campusLink/Resources/marks_logo.png"))); // NOI18N

        javax.swing.GroupLayout searchusrbtnLayout = new javax.swing.GroupLayout(searchusrbtn);
        searchusrbtn.setLayout(searchusrbtnLayout);
        searchusrbtnLayout.setHorizontalGroup(
            searchusrbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchusrbtnLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(searchusrbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchusrbtnLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchusrbtnLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(56, 56, 56))))
        );
        searchusrbtnLayout.setVerticalGroup(
            searchusrbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchusrbtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(38, 38, 38)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        javax.swing.GroupLayout maincardLayout = new javax.swing.GroupLayout(maincard);
        maincard.setLayout(maincardLayout);
        maincardLayout.setHorizontalGroup(
            maincardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maincardLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(maincardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(maincardLayout.createSequentialGroup()
                        .addGroup(maincardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(maincardLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(welcomename))
                    .addGroup(maincardLayout.createSequentialGroup()
                        .addComponent(addusrbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchusrbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(347, Short.MAX_VALUE))
        );
        maincardLayout.setVerticalGroup(
            maincardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maincardLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(maincardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomename)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(maincardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(28, 28, 28)
                .addGroup(maincardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(searchusrbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(addusrbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                .addContainerGap(248, Short.MAX_VALUE))
        );

        cardsL.add(maincard, "card2");

        attendcard.setBackground(new java.awt.Color(245, 192, 0));

        attenTable.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        attenTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        attenTable.setRowHeight(24);
        attenTable.setRowMargin(2);
        attenTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attenTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(attenTable);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(1, 1, 1));
        jLabel3.setText("DATE [DD/MM/YYYY]");

        jButton3.setBackground(new java.awt.Color(1, 1, 1));
        jButton3.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(252, 248, 239));
        jButton3.setText("search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        day.setBackground(new java.awt.Color(252, 248, 239));
        day.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        day.setForeground(new java.awt.Color(1, 1, 1));
        day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        month.setBackground(new java.awt.Color(252, 248, 239));
        month.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        month.setForeground(new java.awt.Color(1, 1, 1));
        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        year.setBackground(new java.awt.Color(252, 248, 239));
        year.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        year.setForeground(new java.awt.Color(1, 1, 1));
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035" }));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jButton3))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(25, 25, 25))
        );

        jPanel8.setBackground(new java.awt.Color(1, 1, 1));

        jLabel33.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(245, 192, 0));
        jLabel33.setText("ATTENDANCE");

        jLabel38.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(252, 248, 239));
        jLabel38.setText("FACULTY > ATTENDANCE POSTING");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jLabel38))
                .addContainerGap(532, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel38)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout attendcardLayout = new javax.swing.GroupLayout(attendcard);
        attendcard.setLayout(attendcardLayout);
        attendcardLayout.setHorizontalGroup(
            attendcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, attendcardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(attendcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        attendcardLayout.setVerticalGroup(
            attendcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attendcardLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );

        cardsL.add(attendcard, "card3");

        studentmarkscard.setBackground(new java.awt.Color(245, 192, 0));

        jPanel10.setBackground(new java.awt.Color(1, 1, 1));

        jLabel34.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(245, 192, 0));
        jLabel34.setText("STUDENT MARKS");

        jLabel39.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(252, 248, 239));
        jLabel39.setText("FACULTY > MARKS POSTING");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(jLabel39))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel39)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        studentMarksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        studentMarksTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentMarksTableMouseClicked(evt);
            }
        });
        studentMarksTable.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                studentMarksTableCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                studentMarksTableInputMethodTextChanged(evt);
            }
        });
        jScrollPane2.setViewportView(studentMarksTable);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        idnoLabel.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        idnoLabel.setForeground(new java.awt.Color(1, 1, 1));
        idnoLabel.setText("REGISTRATION NUMBER");

        jButton2.setBackground(new java.awt.Color(1, 1, 1));
        jButton2.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(252, 248, 239));
        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        regSearch.setBackground(new java.awt.Color(252, 248, 239));
        regSearch.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        regSearch.setForeground(new java.awt.Color(1, 1, 1));
        regSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regSearchActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(1, 1, 1));
        jButton4.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(252, 248, 239));
        jButton4.setText("UPDATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(idnoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(regSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(255, 255, 255))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idnoLabel)
                    .addComponent(regSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout studentmarkscardLayout = new javax.swing.GroupLayout(studentmarkscard);
        studentmarkscard.setLayout(studentmarkscardLayout);
        studentmarkscardLayout.setHorizontalGroup(
            studentmarkscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentmarkscardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentmarkscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        studentmarkscardLayout.setVerticalGroup(
            studentmarkscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentmarkscardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );

        cardsL.add(studentmarkscard, "card4");

        updatecard.setBackground(new java.awt.Color(245, 192, 0));

        jLabel32.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(1, 1, 1));
        jLabel32.setText("BUTTON 3");

        javax.swing.GroupLayout updatecardLayout = new javax.swing.GroupLayout(updatecard);
        updatecard.setLayout(updatecardLayout);
        updatecardLayout.setHorizontalGroup(
            updatecardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatecardLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel32)
                .addContainerGap(667, Short.MAX_VALUE))
        );
        updatecardLayout.setVerticalGroup(
            updatecardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatecardLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel32)
                .addContainerGap(506, Short.MAX_VALUE))
        );

        cardsL.add(updatecard, "card8");

        addusrcard.setBackground(new java.awt.Color(245, 192, 0));

        jLabel17.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(1, 1, 1));
        jLabel17.setText("BUTTON 4");

        javax.swing.GroupLayout addusrcardLayout = new javax.swing.GroupLayout(addusrcard);
        addusrcard.setLayout(addusrcardLayout);
        addusrcardLayout.setHorizontalGroup(
            addusrcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addusrcardLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel17)
                .addContainerGap(672, Short.MAX_VALUE))
        );
        addusrcardLayout.setVerticalGroup(
            addusrcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addusrcardLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel17)
                .addContainerGap(497, Short.MAX_VALUE))
        );

        cardsL.add(addusrcard, "card6");

        resultcard.setBackground(new java.awt.Color(245, 192, 0));

        jLabel20.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(1, 1, 1));
        jLabel20.setText("BUTTON 5");

        javax.swing.GroupLayout resultcardLayout = new javax.swing.GroupLayout(resultcard);
        resultcard.setLayout(resultcardLayout);
        resultcardLayout.setHorizontalGroup(
            resultcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultcardLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel20)
                .addContainerGap(657, Short.MAX_VALUE))
        );
        resultcardLayout.setVerticalGroup(
            resultcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultcardLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel20)
                .addContainerGap(492, Short.MAX_VALUE))
        );

        cardsL.add(resultcard, "card7");

        jSplitPane1.setRightComponent(cardsL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//    private void displayAll()
//    {
//        String date = dateField.getText();
//         String display_query = "SELECT * FROM attendance ";
//        try {
//            // Load the MySQL JDBC driver
//            Class.forName("java.sql.Driver");
//        } catch (ClassNotFoundException e) {
//            // Print the stack trace if an exception is thrown
//            System.out.println(e);
//        }
//        try {
//            // Establish a connection to the database using the URL, username, and password
//            Connection con = DriverManager.getConnection(url, usrn, pass);
//            try ( // Create a statement object to execute the SQL query
//                Statement st = con.createStatement(); ResultSet rs = st.executeQuery(display_query)) {
//                //StringBuilder data = new StringBuilder();
//                boolean found = false;
//                if(rs!=null)
//                {
//                    found = true;
//                   attenTable.setModel(DbUtils.resultSetToTableModel(rs));
//                }
//                if (!found) {
//                    System.out.println("No RECORD FOUND!");
//                    JOptionPane.showMessageDialog(null, "No record found", "Error", JOptionPane.ERROR_MESSAGE);
//                }
//            }
//        } catch (HeadlessException | SQLException e) {
//            // Print the stack trace if an exception is thrown
//            System.out.println(e);
//        }
//        
//        // Create a custom cell renderer
//    DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer() {
//        @Override
//        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
//            // Call the super method to perform default rendering
//            super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
//
//            // Get the value of the specified row and column
//            Object targetValue = table.getValueAt(row, 3);
//
//            // Customize the cell color based on the target value
//            if (targetValue != null && targetValue.toString().equals("absent")) {
//                setBackground(Color.GRAY); // Set the desired background color
//            } else {
//                setBackground(table.getBackground()); // Set the default background color
//            }
//
//            return this;
//        }
//    };
//
//    // Set the cell renderer for the entire row
//    attenTable.setDefaultRenderer(Object.class, cellRenderer);
//
//    // Refresh the table to update the row colors
//    attenTable.repaint();
//    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CardLayout cardLayout = (CardLayout) studentmarkscard.getParent().getLayout();
        cardLayout.show(cardsL,"card2");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addusrbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addusrbtnMouseClicked
        CardLayout cardLayout = (CardLayout) studentmarkscard.getParent().getLayout();
        cardLayout.show(cardsL,"card3");

//            EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                new DatabaseConnection().setVisible(true);
//            }
//        });
//            displayAll();
    }//GEN-LAST:event_addusrbtnMouseClicked

    private void searchusrbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchusrbtnMouseClicked
        CardLayout cardLayout = (CardLayout) studentmarkscard.getParent().getLayout();
        cardLayout.show(cardsL,"card4");
    }//GEN-LAST:event_searchusrbtnMouseClicked

    private void attenTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attenTableMouseClicked
        String dayD = day.getSelectedItem().toString();
        String monthD = month.getSelectedItem().toString();
        String yearD = year.getSelectedItem().toString();
        String date = "D" +"_"+yearD +"_"+ monthD +"_"+ dayD;

        int row = attenTable.getSelectedRow();
        //int column = attenTable.getSelectedColumn();
        String stat = attenTable.getValueAt(row, 4).toString();
        System.out.println(stat);

        if(stat.equals("absent"))
        {
            attenTable.setValueAt("present", row, 4);
        }
        else if(stat.equals("present"))
        {
            attenTable.setValueAt("absent", row, 4);
        }
        else{
            System.out.println("NO VALUE");
        }

        // Create a custom cell renderer
        DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                // Call the super method to perform default rendering
                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                // Get the value of the specified row and column
                Object targetValue = table.getValueAt(row, 4);

                // Customize the cell color based on the target value
                if (targetValue != null && targetValue.toString().equals("absent")) {
                    setBackground(Color.GRAY); // Set the desired background color
                } else {
                    setBackground(table.getBackground()); // Set the default background color
                }

                return this;
            }
        };

        // Set the cell renderer for the entire row
        attenTable.setDefaultRenderer(Object.class, cellRenderer);

        // Refresh the table to update the row colors
        attenTable.repaint();

        if (row < 0) {
            return;
        }

        String fname = attenTable.getValueAt(row, 0).toString();
        String lname = attenTable.getValueAt(row, 1).toString();
        String atten = attenTable.getValueAt(row, 4).toString();
        String regno = attenTable.getValueAt(row, 2).toString();
        String query = "UPDATE attendance SET " + date + " = ? WHERE REGISTRATION_NUMBER = ?";
        try {
            Connection con = DriverManager.getConnection(url, usrn, pass);
            try (PreparedStatement st = con.prepareStatement(query)) {
                st.setString(1, atten);
                st.setString(2, regno);
                int rs = st.executeUpdate();

                if (rs == 0) {
                    System.out.println("No RECORD FOUND!");
                    JOptionPane.showMessageDialog(null, "No record found", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
        //        displayAll();
        //attenTable.setValueAt("present", row, 2);
    }//GEN-LAST:event_attenTableMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String dayD = day.getSelectedItem().toString();
        String monthD = month.getSelectedItem().toString();
        String yearD = year.getSelectedItem().toString();
        String date = "D" +"_"+yearD +"_"+ monthD +"_"+ dayD;
        
        fbe.attenSearchBtn(date);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void studentMarksTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentMarksTableMouseClicked
        int row = studentMarksTable.getSelectedRow();
        int column = studentMarksTable.getSelectedColumn();
        String value = studentMarksTable.getValueAt(row, column).toString();
        System.out.println(value);
        
    }//GEN-LAST:event_studentMarksTableMouseClicked

    private void studentMarksTableCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_studentMarksTableCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_studentMarksTableCaretPositionChanged

    private void studentMarksTableInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_studentMarksTableInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_studentMarksTableInputMethodTextChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String regno = regSearch.getText();
        fbe.marksSearchBtn(regno); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void regSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regSearchActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel model = (DefaultTableModel) studentMarksTable.getModel();

        // Iterate over the rows of the table
        int rowCount = model.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            // Get the values from the table for each row
            String registrationNumber = model.getValueAt(i, 2).toString(); // Assuming registration number is in the third column
            int javaMarks = Integer.parseInt(model.getValueAt(i, 4).toString()); // Assuming Java marks is in the fifth column
            int cLanguageMarks = Integer.parseInt(model.getValueAt(i, 5).toString()); // Assuming C Language marks is in the sixth column
            int cppLanguageMarks = Integer.parseInt(model.getValueAt(i, 6).toString()); // Assuming C++ Language marks is in the seventh column
            int pythonMarks = Integer.parseInt(model.getValueAt(i, 7).toString()); // Assuming Python marks is in the eighth column

            // Construct the update query for each language column
            String updateJavaQuery = "UPDATE studentmarks SET JAVA = " + javaMarks + " WHERE REGISTRATION_NUMBER = '" + registrationNumber + "'";
            String updateCLanguageQuery = "UPDATE studentmarks SET C_Language = " + cLanguageMarks + " WHERE REGISTRATION_NUMBER = '" + registrationNumber + "'";
            String updateCPPLanguageQuery = "UPDATE studentmarks SET CPP_Language = " + cppLanguageMarks + " WHERE REGISTRATION_NUMBER = '" + registrationNumber + "'";
            String updatePythonQuery = "UPDATE studentmarks SET Python = " + pythonMarks + " WHERE REGISTRATION_NUMBER = '" + registrationNumber + "'";

            try (Connection con = DriverManager.getConnection(url, usrn, pass);
                 Statement st = con.createStatement()) {
                // Execute the update queries for each language column
                st.executeUpdate(updateJavaQuery);
                st.executeUpdate(updateCLanguageQuery);
                st.executeUpdate(updateCPPLanguageQuery);
                st.executeUpdate(updatePythonQuery);
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }

        // Display a success message or perform any necessary actions after updating the records
        JOptionPane.showMessageDialog(null, "Records updated successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        CardLayout cardLayout = (CardLayout) studentmarkscard.getParent().getLayout();
        cardLayout.show(cardsL,"card3");
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        CardLayout cardLayout = (CardLayout) studentmarkscard.getParent().getLayout();
        cardLayout.show(cardsL,"card4");
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        int result = JOptionPane.showConfirmDialog(null, "Do you want to Logout?", "Warning!", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            dispose();
            LoginFrame l = new LoginFrame();
        } else {
            //do nothing
        }
    }//GEN-LAST:event_jLabel25MouseClicked
    
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addusrbtn;
    private javax.swing.JPanel addusrcard;
    private javax.swing.JTable attenTable;
    private javax.swing.JPanel attendcard;
    private javax.swing.JPanel cardsL;
    private javax.swing.JComboBox<String> day;
    private javax.swing.JLabel idnoLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel maincard;
    private javax.swing.JComboBox<String> month;
    protected javax.swing.JTextField regSearch;
    private javax.swing.JPanel resultcard;
    private javax.swing.JPanel searchusrbtn;
    private javax.swing.JTable studentMarksTable;
    private javax.swing.JPanel studentmarkscard;
    private javax.swing.JPanel updatecard;
    protected javax.swing.JLabel welcomename;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables

private class FacultyBackEnd{
    void attenSearchBtn(String date)
    {
        boolean found = false;
        
        try (Connection con = DriverManager.getConnection(url, usrn, pass);
            Statement st = con.createStatement()) {

            // Check if the column exists in the table
            DatabaseMetaData metaData = con.getMetaData();
            ResultSet rs = metaData.getColumns(null, null, "attendance", date);
            if (rs.next()) {
                found = true;
            }

            if (found) {
                // Column found, retrieve the data
                String selectQuery = "SELECT FIRST_NAME, LAST_NAME, REGISTRATION_NUMBER, BRANCH, "+date+" FROM attendance";
                PreparedStatement selectStatement = con.prepareStatement(selectQuery);
                rs = selectStatement.executeQuery();
                attenTable.setModel(DbUtils.resultSetToTableModel(rs));
            } else {
                // Column not found, ask user if they want to create a new column
                int confirmed = JOptionPane.showConfirmDialog(null, "No record found for the date '" + date + "'. Do you want to create a new column?", "Confirmation", JOptionPane.YES_NO_OPTION);

                if (confirmed == JOptionPane.YES_OPTION) {
                    // Create the new column
                    String addColumnQuery = "ALTER TABLE attendance ADD COLUMN " + date + " VARCHAR(50) DEFAULT 'absent'";
                    st.executeUpdate(addColumnQuery);

                    // Update the existing rows with the default value
                    String updateRowsQuery = "UPDATE attendance SET " + date + " = 'absent'";
                    st.executeUpdate(updateRowsQuery);

                    // Display the updated table
                    String selectQuery = "SELECT FIRST_NAME, LAST_NAME, REGISTRATION_NUMBER, BRANCH, " + date + " FROM attendance";
                    PreparedStatement selectStatement = con.prepareStatement(selectQuery);
                    rs = selectStatement.executeQuery();
                    attenTable.setModel(DbUtils.resultSetToTableModel(rs));
                } else {
                    System.out.println("No record found!");
                    JOptionPane.showMessageDialog(null, "No record found", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }

        // Create a custom cell renderer
        DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                // Call the super method to perform default rendering
                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                // Get the value of the specified row and column
                Object targetValue = table.getValueAt(row, 4);

                // Customize the cell color based on the target value
                if (targetValue != null && targetValue.toString().equals("absent")) {
                    setBackground(Color.GRAY); // Set the desired background color
                } else {
                    setBackground(table.getBackground()); // Set the default background color
                }

                return this;
            }
        };

        // Set the cell renderer for the entire row
        attenTable.setDefaultRenderer(Object.class, cellRenderer);

        // Refresh the table to update the row colors
        attenTable.repaint();
    }
    
    void marksSearchBtn(String regno)
    {
        String search_query = "select * from studentmarks where REGISTRATION_NUMBER LIKE '%"+regno+"%'";
        try {
                    // Establish a connection to the database using the URL, username, and password
                    Connection con = DriverManager.getConnection(url, usrn, pass);
                    try ( // Create a statement object to execute the SQL query
                            Statement st = con.createStatement(); ResultSet rs = st.executeQuery(search_query)) {
                        
                        boolean found = false;
                        if(rs!=null)
                        {
                            found = true;
                            studentMarksTable.setModel(DbUtils.resultSetToTableModel(rs));
                        }
                        if (!found) {
                            System.out.println("No RECORD FOUND!");
                            JOptionPane.showMessageDialog(null, "No record found", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                } catch (HeadlessException | SQLException e) {
                    // Print the stack trace if an exception is thrown
                    System.out.println(e);
                }             
    }
    
}



}
