/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package campusLink;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author subod
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    
    private static final String url = "jdbc:mysql://127.0.0.1:3306/javaportal?zeroDateTimeBehavior=CONVERT_TO_NULL";
    private static final String usrn = "SAGA";
    private static final String pass = "JAVASAGA@123";
    
    public LoginFrame() {
//        String query1 = "CREATE DATABASE IF NOT EXISTS javaportal";
//        String query2 = "create table IF NOT EXISTS account(userid varchar(30) key , pass varchar(80), role varchar(15), FIRST_NAME varchar(50))";
//        String query3 = "create table IF NOT EXISTS attendance(FIRST_NAME varchar(20), LAST_NAME varchar(20), REGISTRATION_NUMBER varchar(20) key, BRANCH varchar(50))";
//        String query4 = "create table IF NOT EXUSTS settings(id int key, BRANCHE varchar (80), ROLE varchar(80)";
//            
        initComponents();
        setVisible(true);
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("CAMPUS LINK");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        usrDetIn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        passIn = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 192, 0));

        jPanel3.setBackground(new java.awt.Color(1, 1, 1));

        jButton1.setBackground(new java.awt.Color(245, 192, 0));
        jButton1.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(1, 1, 1));
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(245, 192, 0));
        jButton2.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(1, 1, 1));
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(252, 248, 239));
        jLabel1.setText("ID / Registration");

        usrDetIn.setBackground(new java.awt.Color(252, 248, 239));
        usrDetIn.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(252, 248, 239));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Password");

        passIn.setBackground(new java.awt.Color(252, 248, 239));
        passIn.setForeground(new java.awt.Color(1, 1, 1));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(252, 248, 239));
        jLabel4.setText("WELCOME");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(245, 192, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Campus Link");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jButton2)
                            .addGap(18, 18, 18)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(usrDetIn)
                                .addComponent(passIn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel3))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(123, 123, 123))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usrDetIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(192, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        usrDetIn.setText("");
        passIn.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();

                String ref = usrDetIn.getText();
                char[] entpass = passIn.getPassword();
                String password = new String(entpass);
                String search_acc = "SELECT * FROM account WHERE userid = '"+ref+"'";
        
                try {
                        // Load the MySQL JDBC driver
                        Class.forName("java.sql.Driver");
            
                    } catch (ClassNotFoundException e) {
                        // Print the stack trace if an exception is thrown
                        e.printStackTrace();
                    }
                try {
                        // Establish a connection to the database using the URL, username, and password
                        Connection con = DriverManager.getConnection(url, usrn, pass);
                        // Create a statement object to execute the SQL query
                        Statement st = con.createStatement();
                        ResultSet rs = st.executeQuery(search_acc);
                        rs.next();
                        String userpass="";
                        try{
                            userpass = PasswordEncryptDecrypt.decrypt(rs.getString(2));
                        }catch(Exception e)
                        {
                            System.out.println(e);
                        }
                        String inpass = userpass;
                        String display_name = rs.getString(4);
                        String regis = rs.getString(1);
            
                        if(password.equals(inpass))
                        {
                                switch (rs.getString(3)) {
                                        case "STUDENT" -> {
                                                StudentFrame s = new StudentFrame();
                                                s.welcomename.setText(display_name);
                                                s.REGISNO = regis;
                                            }
                                        case "FACULTY" ->                         {
                                                    FacultyFrame f = new FacultyFrame();
                                                    f.welcomename.setText(display_name);
                                                    
                                                }
                                        case "STAFF" ->                         {
                                                    StaffFrame f = new StaffFrame();
                                                    f.welcomename.setText(display_name);
                                                    f.welcomename.setText(display_name);
                                                    f.setVisible(true);
                                                    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                                                    int width = (int) screenSize.getWidth();
                                                    int height = (int) screenSize.getHeight();
                                                    f.setSize(width, height);
                                                    f.setExtendedState(JFrame.MAXIMIZED_BOTH);
                                                    f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                                                    f.idno.setEnabled(false);
                                                }
                                        case "admin" -> {
                                                AdminFrame a = new AdminFrame();
                                                a.welcomename.setText(display_name);
                                                a.setVisible(true);
                                                Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                                                int width = (int) screenSize.getWidth();
                                                int height = (int) screenSize.getHeight();
                                                a.setSize(width, height);
                                                a.setExtendedState(JFrame.MAXIMIZED_BOTH);
                                                a.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                                                a.idno.setEnabled(false);
                                            }
                                        default -> {
                                            }
                                    }
                            }
                        else
                        {
                                JOptionPane.showMessageDialog(null, "Wrong UserName or password", "Error", JOptionPane.ERROR_MESSAGE);
                                LoginFrame lf = new LoginFrame();
                            }
                        rs.close();
                        st.close();
                    } catch (SQLException e) {
                        // Print the stack trace if an exception is thrown
                        //e.printStackTrace();
                        JOptionPane.showMessageDialog(null, "Wrong UserName or password", "Error", JOptionPane.ERROR_MESSAGE);
                        LoginFrame lf = new LoginFrame();
            
                    }
        //AdminFrame a = new AdminFrame();
        //FacultyFrame f = new FacultyFrame();
        //StudentFrame s = new StudentFrame();
        //s.REGISNO = "AP21000000001";
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        LoginFrame l = new LoginFrame();    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField passIn;
    private javax.swing.JTextField usrDetIn;
    // End of variables declaration//GEN-END:variables
}


